### ISSUE TITLE
plugin configuration issue

### ISSUE THREAD

**Issue by agsmorodin** [cnenning/go-artifactory-scm-plugin#1]
Hi,

After plugin installation I don't see any configuration which is related to artifactory.  List of materials still has the same structure,  without artifactory scm.  Also I didn't manage to find any global configurations that are related to this plugin. 
Could you please advise the steps how to configure plugin or I am missing something?

**Comment by cnenning** [comment]
![screenshot-go-plugin-arti-scm](https://cloud.githubusercontent.com/assets/15086255/20215868/9ac746dc-a817-11e6-986b-5964d8a2b8dd.png)

After a pipeline has been created you can see the plugin when adding a material. Unfortunately you have to create the pipeline with a dummy git material first (not sure why, a bug in go itself?). The git material can be removed afterwards.

I'm going to update README.MD later.
