### ISSUE TITLE
How do I pull a particular version

### ISSUE THREAD

**Issue by mattcotton-justgiving** [cnenning/go-artifactory-scm-plugin#20]
I'm trying to use go-artifactory-scm-plugin.
It's all working for the latest version but how do I set a pipeline to use a specific version e.g. I have version folders 1.1.10, 1.1.11 and 1.1.12. I want to use version 1.1.10. I've set the environment variable VERSION=1.1.10 in GOCD but the pipeline always pulls the latest version (1.1.12 in this case).

What do I need to do to pull a specific version?

Thanks

**Comment by mattcotton-justgiving** [comment]
update:
If I put a value like '1.1.10' in the Version regex field (in the material) and press 'Check connection' it comes back with matching 1.1.10. All good.
But when the pipeline runs it fails to pull anything from artifactory.
I see the following in the pipeline logs:

```
09:45:42.663 [go] setting environment variable 'GO_SCM_STANDARD_DEPLOY_LABEL' to value 'bad data, check logs'
...
09:45:42.663 [go] setting environment variable 'GO_SCM_STANDARD_DEPLOY_VERSION_REGEX' to value '1.0.11'
```

**Comment by cnenning** [comment]
It seems you have defined a `package material`. That is intended to download latest version only. To choose a specific version you need to create a material of type `Artifactory SCM`, see screenshot in README of this project. Note that you must use a specific directory structure in artifactory for this plugin to find your versions.

**Comment by mattcotton-justgiving** [comment]
No, it's definitely an Artifactory SCM material.

![artifactory](https://user-images.githubusercontent.com/12623669/34151634-ce517102-e4a3-11e7-8e75-4f4791a069df.png)

It's all working when not specifying a version regex. But doesn't pull anything when specifying a version regex.

**Comment by mattcotton-justgiving** [comment]
I found the issue. The version regex needs to be of the format "1.1.10/*.*" rather than "1.1.10".
