### ISSUE TITLE
gocd17.11 setting proxy url, but plugin does not through proxy

### ISSUE THREAD

**Issue by liushujuan** [cnenning/go-artifactory-scm-plugin#22]
gocd server version:17.11
setting Proxy URL
But found the plugin does not through proxy.
We see go-server.log and confirm our environment variables is through proxy
In plugin-artifactory-pkg.log we see it does not through proxy

**Comment by liushujuan** [comment]
We resolve now, if you config proxy in GUI, you should restart go server to support.

**Comment by cnenning** [comment]
Happy that it works 😃 
I added a section about this in Readme.
