### ISSUE TITLE
Having issues with fetching the correct artifactory artifact

### ISSUE THREAD

**Issue by mattcotton-justgiving** [cnenning/go-artifactory-scm-plugin#23]
This is a continuation of [Issue 21](https://github.com/cnenning/go-artifactory-scm-plugin/issues/21).

Sometimes the plugin doesn't pull anything when a pipeline runs (I don't see any of the logging in the pipeline logs). This may be due to the SocketTimeout I mention later.

Sometimes it pulls old versions of the artifact. This is an ongoing issue and related to issue 21.

I've done all the things we discussed in issue 21. Increased the socket timeout to 5000. Restarted the GO server. I've deleted and re-added the material. It still fetches an old version of the artifact.

I've looked in the GOCD and plugin logs. Here are some interesting lines:

**go-server.log**
`2018-03-21 16:18:47,924  INFO [94@MessageListener for MaterialUpdateListener] MaterialRepository:857 - Saving revisions for material [[dummy_id=donation, url=http://artifactory.justgiving.com:80/artifactory/int-Files/justgiving/helm/]] after removing the following duplicates [1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.20, 1.0.21, 1.0.22, 1.0.23, 1.0.24, 1.0.25, 1.0.26, 1.0.27, 1.0.28, 1.0.29, 1.0.30, 1.0.31, 1.0.32]`

It's version 1.0.32 that I need. Why does it say they are duplicates (I know this is GOCD code, not your plugin).

**plugin-artifactory-scm.log**
`2018-03-21 13:03:11,331 ERROR [91@MessageListener for MaterialUpdateListener] ArtifactoryScmPlugin:77 - ERROR!
        request name: latest-revisions-since
        request body: {"scm-configuration":{"password":{"value":"xxxxx"},"dummy_id":{"value":"recurring-channels"},"url":{"value":"http://artifactory.justgi
ving.com:80/artifactory/int-Files/justgiving/helm/"},"username":{"value":"xxxxx"}},"scm-data":{},"flyweight-folder":"/mnt/go-server/pipelines/flyweight/47ed6d68-dfe4-45d
3-96a5-1c3aec72d3c9","previous-revision":{"revision":"1.0.32","timestamp":"2018-03-14T14:18:00.000Z","data":{}}}
java.net.SocketTimeoutException: Read timed out`

I was having the above errors quite a bit but haven't seen them since changing the plugin config settings to:
`2018-03-21 13:45:04,805  INFO [Thread-75] ArtifactoryScmPlugin:52 - setting connectTimeout: 240
2018-03-21 13:45:04,805  INFO [Thread-75] ArtifactoryScmPlugin:52 - setting socketTimeout: 5000
2018-03-21 13:45:04,806  INFO [Thread-75] ArtifactoryScmPlugin:52 - setting connectionRequestTimeout: 240
2018-03-21 13:45:04,806  INFO [Thread-75] ArtifactoryScmPlugin:52 - setting ConnPoolSize: 5` 

Any help much appreciated.

**Comment by mattcotton-justgiving** [comment]
I think the issue is related to the revision that GOCD seems to store against a material. In the Value Stream View for the failing pipeline I see that GOCD is storing 1.0.9 as the revision for the Artifactory SCM material. This is consistent with the version that is fetched when looking at the pipeline stdout.

Does this make sense to you? Is there a way of ignoring this revision and always fetching latest for the Artifactory SCM material?

**Comment by wolpi** [comment]
> but haven't seen them since changing the plugin config settings

That is important. As long as there are exceptions go does weird things.

> Why does it say they are duplicates

Sounds interesting, never seen this myself. Can you share the HTML that is returned by `http://artifactory.justgi ving.com:80/artifactory/int-Files/justgiving/helm/` when accessed with your username and password?

> I think the issue is related to the revision that GOCD seems to store against a material.

Yes, that is surly the behavior of go. Version 1.0.9 was the last one go considered as "not broken" and that is the one it uses. That is the behavior I have seen when exceptions occur. The usual way to fix this is to make sure there are no more exceptions and re-creating materials. As go does fancy validations and consistency checks it is often not possible to just delete and re-add a material. In such a case you must use different values for material "id fields". That is one reason why "dummy id" exists.

When you re-added the material, did you change "dummy id"?

**Comment by cnenning** [comment]
no response in quite some time, I'm closing this now
